/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentAttemptSettings struct {
	RandomizeQuestions bool `json:"randomizeQuestions,omitempty"`

	ShowResults bool `json:"showResults,omitempty"`

	PreventTabSwitching bool `json:"preventTabSwitching,omitempty"`

	RequireWebcam bool `json:"requireWebcam,omitempty"`
}
