/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type Question struct {
	Id int64 `json:"id"`

	Type_ string `json:"type"`

	Text string `json:"text"`

	Options []QuestionOption `json:"options,omitempty"`

	CorrectAnswer *OneOfQuestionCorrectAnswer `json:"correctAnswer,omitempty"`

	Points int32 `json:"points,omitempty"`
}
