/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentStatisticsBySubject struct {
	Subject string `json:"subject,omitempty"`

	Count int32 `json:"count,omitempty"`
}
