/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentSettingsRequest struct {
	RandomizeQuestions bool `json:"randomizeQuestions,omitempty"`

	ShowResults bool `json:"showResults,omitempty"`

	AllowRetake bool `json:"allowRetake,omitempty"`

	MaxAttempts int32 `json:"maxAttempts,omitempty"`

	TimeLimitEnforced bool `json:"timeLimitEnforced,omitempty"`

	RequireWebcam bool `json:"requireWebcam,omitempty"`

	PreventTabSwitching bool `json:"preventTabSwitching,omitempty"`

	RequireIdentityVerification bool `json:"requireIdentityVerification,omitempty"`
}
