/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentPerformanceAnalyticsMostChallenging struct {
	AssessmentId int64 `json:"assessmentId,omitempty"`

	Title string `json:"title,omitempty"`

	AvgScore float32 `json:"avgScore,omitempty"`
}
