/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type StudentQuestion struct {
	Id int64 `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`

	Text string `json:"text,omitempty"`

	Options []QuestionOption `json:"options,omitempty"`
}
