/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type QuestionOption struct {
	Id string `json:"id"`

	Text string `json:"text"`
}
