/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	"time"
)

type AssessmentAttempt struct {
	AttemptId int64 `json:"attemptId,omitempty"`

	AssessmentId int64 `json:"assessmentId,omitempty"`

	Title string `json:"title,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	TimeLimit bool `json:"timeLimit,omitempty"`

	EndsAt time.Time `json:"endsAt,omitempty"`

	Questions []StudentQuestion `json:"questions,omitempty"`

	Settings *AssessmentAttemptSettings `json:"settings,omitempty"`
}
