/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentPage struct {
	Content []AssessmentSummary `json:"content,omitempty"`

	Pageable *PageableObject `json:"pageable,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`

	TotalElements int32 `json:"totalElements,omitempty"`

	Last bool `json:"last,omitempty"`

	First bool `json:"first,omitempty"`

	Sort *SortObject `json:"sort,omitempty"`

	Number int32 `json:"number,omitempty"`

	NumberOfElements int32 `json:"numberOfElements,omitempty"`

	Size int32 `json:"size,omitempty"`

	Empty bool `json:"empty,omitempty"`
}
