/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentStatistics struct {
	TotalAssessments int32 `json:"totalAssessments,omitempty"`

	ActiveAssessments int32 `json:"activeAssessments,omitempty"`

	DraftAssessments int32 `json:"draftAssessments,omitempty"`

	ExpiredAssessments int32 `json:"expiredAssessments,omitempty"`

	TotalAttempts int32 `json:"totalAttempts,omitempty"`

	PassRate float32 `json:"passRate,omitempty"`

	AverageScore float32 `json:"averageScore,omitempty"`

	BySubject []AssessmentStatisticsBySubject `json:"bySubject,omitempty"`
}
