/*
 * Secure Assessment Platform API
 *
 * API for managing secure online assessments with proctoring features
 *
 * API version: 1.0.0
 * Contact: support@secureassessment.example
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type AssessmentPerformanceAnalytics struct {
	AssessmentCompletionRates []AssessmentPerformanceAnalyticsAssessmentCompletionRates `json:"assessmentCompletionRates,omitempty"`

	ScoreDistribution []AssessmentPerformanceAnalyticsScoreDistribution `json:"scoreDistribution,omitempty"`

	AverageTimeSpent float32 `json:"averageTimeSpent,omitempty"`

	MostChallenging []AssessmentPerformanceAnalyticsMostChallenging `json:"mostChallenging,omitempty"`

	MostSuccessful []AssessmentPerformanceAnalyticsMostSuccessful `json:"mostSuccessful,omitempty"`
}
